// <auto-generated />
using System;
using ContentGen.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ContentGen.Infrastructure.Migrations
{
    [DbContext(typeof(ContentDbContext))]
    [Migration("20260608143626_AddPostPublication")]
    partial class AddPostPublication
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("ContentGen.Domain.Entities.ArticleRawContent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Articles");
                });

            modelBuilder.Entity("ContentGen.Domain.Entities.PostPublication", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ArticleId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PostIndex")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ArticleId", "Language", "PostIndex")
                        .IsUnique();

                    b.ToTable("PostPublications");
                });

            modelBuilder.Entity("ContentGen.Domain.Entities.ProcessedContent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ArticleId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CasualExplanationEnUS")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CasualExplanationPtBR")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("InsightsEnUS")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("InsightsPtBR")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PostSuggestionsEnUS")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PostSuggestionsPtBR")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TechnicalSummaryEnUS")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TechnicalSummaryPtBR")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ArticleId")
                        .IsUnique();

                    b.ToTable("ProcessedContents");
                });

            modelBuilder.Entity("ContentGen.Domain.Entities.ProcessedContent", b =>
                {
                    b.HasOne("ContentGen.Domain.Entities.ArticleRawContent", "Article")
                        .WithOne()
                        .HasForeignKey("ContentGen.Domain.Entities.ProcessedContent", "ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Article");
                });
#pragma warning restore 612, 618
        }
    }
}
